# Config file for automatic testing at travis-ci.org

language: python
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

env:
  # Lowest supported version
  - MARSHMALLOW_VERSION="==2.7.0"
  # Latest release
  - MARSHMALLOW_VERSION=""

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

install:
    - travis_retry pip install -U .
    - if [[ $TRAVIS_PYTHON_VERSION == 2* || $TRAVIS_PYTHON_VERSION == 'pypy' || $TRAVIS_PYTHON_VERSION == '3.3' ]]; then travis_retry pip install -r dev-requirements.txt; fi
    # NOTE: aiohttp is not supported on 3.3
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then travis_retry pip install -r dev-requirements-py3.txt; fi
    - travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre


script: invoke test
deploy:
  provider: pypi
  user: sloria
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  password:
    secure: TMeTi5OPl2cYsl5hNP4w1xESd2vQUOy8NgZ0c3KbrVSSeBuUCGOKyYJZNGzD9KDMucCvYFuxCwYiDxP8tB5iT85z3rhdVkzppZTy3/3kXMODjlhMzqTnCdJSOoZZ+D5/Y3Zqb8QxU78NggPutfX4bbUU/wNsVbdODXWHe5y2q3k=
